{
 "title": "Marzban V1.0.0",
 "description": "this is dashboard for marzban pannel with mysql",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  { "title": "Status now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT COUNT(id) 'Online Users', online_at FROM users where online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE) group by online_at"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT c.node,\r\n       count(a.id) 'users'\r\nFROM users AS a\r\nLEFT JOIN (\r\n    SELECT\r\n        user_id,\r\n        IFNULL(n.name, 'Main') AS node,\r\n        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY node_id) AS row_num\r\n    FROM node_user_usages AS a\r\n    LEFT JOIN nodes AS n ON n.id = a.node_id\r\n    WHERE DATE(a.created_at) = CURDATE()\r\n        AND HOUR(a.created_at) = HOUR(NOW())\r\n) AS c ON c.row_num = 1 AND c.user_id = a.id\r\nWHERE online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\ngroup by c.node\r\n"
    }
   ]
  },
  {
   "title": "Admin List",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  username as \"Name\",\r\n  CASE \r\n    WHEN users_usage >= 1099511627776 THEN CONCAT(ROUND(users_usage / 1099511627776, 2), ' TB')\r\n    WHEN users_usage >= 1073741824 THEN CONCAT(ROUND(users_usage / 1073741824, 2), ' GB')\r\n    WHEN users_usage >= 1048576 THEN CONCAT(ROUND(users_usage / 1048576, 2), ' MB')\r\n    ELSE CONCAT(users_usage, ' B')\r\n  END AS \"Usage\",\r\n  (SELECT COUNT(*) FROM users WHERE admin_id = admins.id) AS \"Users\"\r\nFROM \r\n  admins\r\n"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "table",
   "description": "Status Lists Nodes",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT name as 'Server Name', status as 'Status', xray_version as 'Xray Version'\r\nFROM nodes \r\nWHERE status IN ('error', 'connecting', 'disabled', 'connected') \r\nORDER BY status DESC;\r\n"
    }
   ]
  },
  {
   "title": "Data Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT\r\n  CASE \r\n    WHEN downlink >= POWER(1024, 4) THEN CONCAT(ROUND(downlink / POWER(1024, 4), 2), ' TB')\r\n    WHEN downlink >= POWER(1024, 3) THEN CONCAT(ROUND(downlink / POWER(1024, 3), 2), ' GB')\r\n    WHEN downlink >= POWER(1024, 2) THEN CONCAT(ROUND(downlink / POWER(1024, 2), 2), ' MB')\r\n    ELSE CONCAT(ROUND(downlink / 1024, 2), ' KB')\r\n  END AS \"Download\",\r\n\r\n  CASE \r\n    WHEN uplink >= POWER(1024, 4) THEN CONCAT(ROUND(uplink / POWER(1024, 4), 2), ' TB')\r\n    WHEN uplink >= POWER(1024, 3) THEN CONCAT(ROUND(uplink / POWER(1024, 3), 2), ' GB')\r\n    WHEN uplink >= POWER(1024, 2) THEN CONCAT(ROUND(uplink / POWER(1024, 2), 2), ' MB')\r\n    ELSE CONCAT(ROUND(uplink / 1024, 2), ' KB')\r\n  END AS \"Upload\"\r\n  \r\nFROM `system`;"
    }
   ]
  },
  {
   "title": "Connections by Client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT b.type 'Client',\r\n       count(a.id) 'Users'\r\nFROM users AS a\r\nLEFT JOIN (\r\n    SELECT DISTINCT \r\n           sub_last_user_agent,\r\n           CASE \r\n               WHEN sub_last_user_agent IS NULL OR TRIM(sub_last_user_agent) = '' THEN 'Unknown'  \r\n               ELSE SUBSTR(sub_last_user_agent, 1, INSTR(sub_last_user_agent, '/')-1)\r\n           END AS type\r\n    FROM users\r\n) AS b ON b.sub_last_user_agent = a.sub_last_user_agent\r\nWHERE online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\n\r\ngroup by b.type\r\n"
    }
   ]
  },
  { "title": "Today stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Today users",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select SUM(`a`.`used_traffic`) AS `used_traffic`,\r\n                            ifnull(`n`.`name`, 'Main') AS `node`\r\n                        from ( (\r\n                                    `node_user_usages` `a`\r\n                                    left join `users` `u` on( (`u`.`id` = `a`.`user_id`))\r\n                                )\r\n                                left join `nodes` `n` on( (`n`.`id` = `a`.`node_id`))\r\n                            )\r\n                        where (\r\n                                `a`.`created_at` >= concat( curdate(),' 00:00:00'\r\n                                )\r\n                            )\r\n                            group by ifnull(`n`.`name`, 'Main')"
    }
   ]
  },
  {
   "title": "Traffic by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select \r\nifnull(`n`.`name`, 'Main') AS `Node`,\r\nSUM(`a`.`used_traffic`) AS `Traffic`\r\nfrom ((`node_user_usages` `a` left join `users` `u` on( (`u`.`id` = `a`.`user_id`))) left join `nodes` `n` on( (`n`.`id` = `a`.`node_id`)))\r\nwhere (`a`.`created_at` >= concat( curdate(),' 00:00:00'))group by ifnull(`n`.`name`, 'Main')"
    }
   ]
  },
  {
   "title": "Traffic by time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select a.created_at 'Datetime', sum(a.used_traffic) 'Traffic' from node_user_usages a\r\njoin nodes n on n.id = a.node_id\r\nwhere a.created_at >= concat( curdate(),' 00:00:00')\r\ngroup by a.created_at\r\norder by a.created_at ASC\r\n"
    }
   ]
  },
  {
   "title": "Connections by time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select a.created_at 'Datetime', count(a.created_at) from node_user_usages a where a.created_at >= concat( curdate(),' 00:00:00') group by a.created_at \r\norder by a.created_at ASC"
    }
   ]
  }
 ]
}