{
 "title": "Marzban Sudo V2.0.0",
 "description": "this is dashboard for marzban pannel with mysql",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  { "title": "Status now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT COUNT(id) 'Online Users', online_at FROM users WHERE online_at >= DATE_SUB(NOW(), INTERVAL 60 SECOND) GROUP BY online_at;\r\n"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n    nodes.node,\r\n    COALESCE(COUNT(online_users.id), 0) AS users\r\nFROM (\r\n    SELECT DISTINCT IFNULL(n.name, 'Main') AS node FROM nodes n\r\n) AS nodes\r\nLEFT JOIN (\r\n    SELECT \r\n        u.id,\r\n        IFNULL(n.name, 'Main') AS node\r\n    FROM users u\r\n    LEFT JOIN node_user_usages nuu ON nuu.user_id = u.id\r\n    LEFT JOIN nodes n ON n.id = nuu.node_id\r\n    WHERE u.online_at >= DATE_SUB(NOW(), INTERVAL 60 SECOND)\r\n      AND DATE(nuu.created_at) = CURDATE()\r\n      AND HOUR(nuu.created_at) = HOUR(NOW())\r\n) AS online_users ON nodes.node = online_users.node\r\nGROUP BY nodes.node;\r\n"
    }
   ]
  },
  {
   "title": "Connections by Client",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT b.type 'Client',\r\n       count(a.id) 'Users'\r\nFROM users AS a\r\nLEFT JOIN (\r\n    SELECT DISTINCT \r\n           sub_last_user_agent,\r\n           CASE \r\n               WHEN sub_last_user_agent IS NULL OR TRIM(sub_last_user_agent) = '' THEN 'Unknown'  \r\n               ELSE SUBSTR(sub_last_user_agent, 1, INSTR(sub_last_user_agent, '/')-1)\r\n           END AS type\r\n    FROM users\r\n) AS b ON b.sub_last_user_agent = a.sub_last_user_agent\r\nWHERE online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\ngroup by b.type\r\n"
    }
   ]
  },
  {
   "title": "All Users Status",
   "type": "bargauge",
   "description": "وضعیت یوزرهای شما",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n    u.status AS \"User Status\", \r\n    COUNT(u.id) AS \"User Count\"\r\nFROM \r\n    users u\r\nGROUP BY \r\n    u.status;\r\n"
    }
   ]
  },
  {
   "title": "All Used Traffic Overview",
   "type": "stat",
   "description": "حجم کل مصرفی یوزرهای شما (این بخش ریست نخواهد شد)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN SUM(used_traffic) >= 1125899906842624 THEN CONCAT(ROUND(SUM(used_traffic) / 1125899906842624, 2), ' PB')\r\n    WHEN SUM(used_traffic) >= 1099511627776 THEN CONCAT(ROUND(SUM(used_traffic) / 1099511627776, 2), ' TB')\r\n    WHEN SUM(used_traffic) >= 1073741824 THEN CONCAT(ROUND(SUM(used_traffic) / 1073741824, 2), ' GB')\r\n    WHEN SUM(used_traffic) >= 1048576 THEN CONCAT(ROUND(SUM(used_traffic) / 1048576, 2), ' MB')\r\n    WHEN SUM(used_traffic) >= 1024 THEN CONCAT(ROUND(SUM(used_traffic) / 1024, 2), ' KB')\r\n    ELSE CONCAT(SUM(used_traffic), ' B')\r\n  END AS total_used_traffic\r\nFROM users;\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Panel Data Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT\r\n  CASE \r\n    WHEN downlink >= POWER(1024, 5) THEN CONCAT(ROUND(downlink / POWER(1024, 5), 2), ' PB')\r\n    WHEN downlink >= POWER(1024, 4) THEN CONCAT(ROUND(downlink / POWER(1024, 4), 2), ' TB')\r\n    WHEN downlink >= POWER(1024, 3) THEN CONCAT(ROUND(downlink / POWER(1024, 3), 2), ' GB')\r\n    WHEN downlink >= POWER(1024, 2) THEN CONCAT(ROUND(downlink / POWER(1024, 2), 2), ' MB')\r\n    ELSE CONCAT(ROUND(downlink / 1024, 2), ' KB')\r\n  END AS \"Download\",\r\n\r\n  CASE \r\n    WHEN uplink >= POWER(1024, 5) THEN CONCAT(ROUND(uplink / POWER(1024, 5), 2), ' PB')\r\n    WHEN uplink >= POWER(1024, 4) THEN CONCAT(ROUND(uplink / POWER(1024, 4), 2), ' TB')\r\n    WHEN uplink >= POWER(1024, 3) THEN CONCAT(ROUND(uplink / POWER(1024, 3), 2), ' GB')\r\n    WHEN uplink >= POWER(1024, 2) THEN CONCAT(ROUND(uplink / POWER(1024, 2), 2), ' MB')\r\n    ELSE CONCAT(ROUND(uplink / 1024, 2), ' KB')\r\n  END AS \"Upload\"\r\n  \r\nFROM `system`;\r\n"
    }
   ]
  },
  {
   "title": "All Data Allocation Overview",
   "type": "stat",
   "description": "این قسمت جمع کل حجم های ساخته شده شما هست",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN SUM(data_limit) >= 1125899906842624 THEN CONCAT(ROUND(SUM(data_limit) / 1125899906842624, 2), ' PB')\r\n    WHEN SUM(data_limit) >= 1099511627776 THEN CONCAT(ROUND(SUM(data_limit) / 1099511627776, 2), ' TB')\r\n    WHEN SUM(data_limit) >= 1073741824 THEN CONCAT(ROUND(SUM(data_limit) / 1073741824, 2), ' GB')\r\n    WHEN SUM(data_limit) >= 1048576 THEN CONCAT(ROUND(SUM(data_limit) / 1048576, 2), ' MB')\r\n    WHEN SUM(data_limit) >= 1024 THEN CONCAT(ROUND(SUM(data_limit) / 1024, 2), ' KB')\r\n    ELSE CONCAT(SUM(data_limit), ' B')\r\n  END AS total_data_limit\r\nFROM users;\r\n"
    }
   ]
  },
  {
   "title": "Today Status (Reset Every 24h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Today users",
     "type": "geomap",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 138 },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "select SUM(`a`.`used_traffic`) AS `used_traffic`,\r\n                            ifnull(`n`.`name`, 'Main') AS `node`\r\n                        from ( (\r\n                                    `node_user_usages` `a`\r\n                                    left join `users` `u` on( (`u`.`id` = `a`.`user_id`))\r\n                                )\r\n                                left join `nodes` `n` on( (`n`.`id` = `a`.`node_id`))\r\n                            )\r\n                        where (\r\n                                `a`.`created_at` >= concat( curdate(),' 00:00:00'\r\n                                )\r\n                            )\r\n                            group by ifnull(`n`.`name`, 'Main')"
      }
     ]
    },
    {
     "title": "Traffic by Node",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 6, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "SELECT \r\n    IFNULL(`n`.`name`, 'Main') AS `Node`,\r\n    SUM(`a`.`used_traffic`) AS `Traffic`\r\nFROM \r\n    (`node_user_usages` `a` \r\n    LEFT JOIN `users` `u` ON `u`.`id` = `a`.`user_id`) \r\n    LEFT JOIN `nodes` `n` ON `n`.`id` = `a`.`node_id`\r\nWHERE \r\n    CONVERT_TZ(`a`.`created_at`, '+00:00', '+03:30') >= CONCAT(DATE(CONVERT_TZ(NOW(), '+00:00', '+03:30')), ' 00:00:00')\r\nGROUP BY \r\n    IFNULL(`n`.`name`, 'Main');\r\n"
      }
     ]
    },
    {
     "title": "Traffic by time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "select a.created_at 'Datetime', sum(a.used_traffic) 'Traffic' from node_user_usages a\r\njoin nodes n on n.id = a.node_id\r\nwhere a.created_at >= concat( curdate(),' 00:00:00')\r\ngroup by a.created_at\r\norder by a.created_at ASC\r\n"
      }
     ]
    },
    {
     "title": "Connections by time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "select a.created_at 'Datetime', count(a.created_at) from node_user_usages a where a.created_at >= concat( curdate(),' 00:00:00') group by a.created_at \r\norder by a.created_at ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Admin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Admin List",
     "type": "table",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 227 },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "SELECT \r\n  username as \"Name\",\r\n  CASE \r\n    WHEN users_usage >= 1099511627776 THEN CONCAT(ROUND(users_usage / 1099511627776, 2), ' TB')\r\n    WHEN users_usage >= 1073741824 THEN CONCAT(ROUND(users_usage / 1073741824, 2), ' GB')\r\n    WHEN users_usage >= 1048576 THEN CONCAT(ROUND(users_usage / 1048576, 2), ' MB')\r\n    ELSE CONCAT(users_usage, ' B')\r\n  END AS \"Usage\",\r\n  (SELECT COUNT(*) FROM users WHERE admin_id = admins.id) AS \"Users\"\r\nFROM \r\n  admins\r\n"
      }
     ]
    },
    {
     "title": "Reseted Traffic",
     "type": "table",
     "description": "اطلاعات شما در این بخش (مصرف حجم شما درصورت تمدید ریست خواهد شد)",
     "gridPos": { "h": 16, "w": 7, "x": 8, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "SELECT \r\n    ad.username AS 'Admin Name',\r\n    a.reset_at,\r\n    CASE \r\n        WHEN a.used_traffic_at_reset >= POWER(1024, 4) THEN CONCAT(ROUND(a.used_traffic_at_reset / POWER(1024, 4), 2), ' TB')\r\n        WHEN a.used_traffic_at_reset >= POWER(1024, 3) THEN CONCAT(ROUND(a.used_traffic_at_reset / POWER(1024, 3), 2), ' GB')\r\n        WHEN a.used_traffic_at_reset >= POWER(1024, 2) THEN CONCAT(ROUND(a.used_traffic_at_reset / POWER(1024, 2), 2), ' MB')\r\n        ELSE CONCAT(ROUND(a.used_traffic_at_reset / 1024, 2), ' KB')\r\n    END AS 'Used Traffic'\r\nFROM \r\n    admin_usage_logs a\r\nJOIN \r\n    admins ad ON a.admin_id = ad.id\r\nORDER BY \r\n    a.reset_at DESC;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users Onlines",
     "type": "table",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 244 },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "SELECT \r\n    users.username AS 'Name',\r\n\r\n    CASE\r\n        WHEN used_traffic >= 1099511627776 THEN CONCAT(ROUND(used_traffic / 1099511627776, 2), ' TB')\r\n        WHEN used_traffic >= 1073741824 THEN CONCAT(ROUND(used_traffic / 1073741824, 2), ' GB')\r\n        WHEN used_traffic >= 1048576 THEN CONCAT(ROUND(used_traffic / 1048576, 2), ' MB')\r\n        WHEN used_traffic >= 1024 THEN CONCAT(ROUND(used_traffic / 1024, 2), ' KB')\r\n        ELSE CONCAT(used_traffic, ' B')\r\n    END AS 'Data Used',\r\n\r\n    CASE\r\n        WHEN data_limit IS NULL THEN 'Unlimited'\r\n        WHEN data_limit >= 1099511627776 THEN CONCAT(ROUND(data_limit / 1099511627776, 2), ' TB')\r\n        WHEN data_limit >= 1073741824 THEN CONCAT(ROUND(data_limit / 1073741824, 2), ' GB')\r\n        WHEN data_limit >= 1048576 THEN CONCAT(ROUND(data_limit / 1048576, 2), ' MB')\r\n        WHEN data_limit >= 1024 THEN CONCAT(ROUND(data_limit / 1024, 2), ' KB')\r\n        ELSE CONCAT(data_limit, ' B')\r\n    END AS 'Data Limit',\r\n\r\n    CASE\r\n        WHEN expire IS NULL THEN 'Unlimited'\r\n        WHEN FROM_UNIXTIME(expire) < NOW() THEN 'Expired'\r\n        ELSE CONCAT(\r\n            FLOOR(TIMESTAMPDIFF(MINUTE, NOW(), FROM_UNIXTIME(expire)) / (60 * 24)), ' Day ',\r\n            MOD(FLOOR(TIMESTAMPDIFF(MINUTE, NOW(), FROM_UNIXTIME(expire)) / 60), 24), ' Hour ',\r\n            MOD(TIMESTAMPDIFF(MINUTE, NOW(), FROM_UNIXTIME(expire)), 60), ' Minute'\r\n        )\r\n    END AS 'Expire',\r\n\r\n    COALESCE(admins.username, 'Unknown') AS 'Admin Name',\r\n    users.sub_last_user_agent AS 'User Agent'\r\n\r\nFROM users\r\nLEFT JOIN admins ON users.admin_id = admins.id\r\n\r\nWHERE \r\n    users.status = 'active' \r\n    AND users.online_at >= DATE_SUB(NOW(), INTERVAL 60 SECOND)\r\n\r\nORDER BY users.online_at DESC\r\nLIMIT 100;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Status",
     "type": "table",
     "description": "Status Lists Nodes",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 257 },
     "targets": [
      {
       "dataset": "marzban",
       "rawSql": "SELECT \r\n    n.name AS 'Server Name',\r\n    n.status AS 'Status',\r\n    n.xray_version AS 'Xray Version',\r\n    CASE\r\n        WHEN SUM(u.uplink) < 1024 * 1024 * 1024 THEN CONCAT(ROUND(SUM(u.uplink) / 1024 / 1024, 2), ' MB')\r\n        WHEN SUM(u.uplink) < 1024 * 1024 * 1024 * 1024 THEN CONCAT(ROUND(SUM(u.uplink) / 1024 / 1024 / 1024, 2), ' GB')\r\n        ELSE CONCAT(ROUND(SUM(u.uplink) / 1024 / 1024 / 1024 / 1024, 2), ' TB')\r\n    END AS 'Total Uplink',\r\n    CASE\r\n        WHEN SUM(u.downlink) < 1024 * 1024 * 1024 THEN CONCAT(ROUND(SUM(u.downlink) / 1024 / 1024, 2), ' MB')\r\n        WHEN SUM(u.downlink) < 1024 * 1024 * 1024 * 1024 THEN CONCAT(ROUND(SUM(u.downlink) / 1024 / 1024 / 1024, 2), ' GB')\r\n        ELSE CONCAT(ROUND(SUM(u.downlink) / 1024 / 1024 / 1024 / 1024, 2), ' TB')\r\n    END AS 'Total Downlink'\r\nFROM \r\n    nodes n\r\nLEFT JOIN \r\n    node_usages u ON n.id = u.node_id\r\nWHERE \r\n    n.status IN ('error', 'connecting', 'disabled', 'connected')\r\nGROUP BY \r\n    n.name, n.status, n.xray_version\r\nORDER BY \r\n    n.status DESC;\r\n"
      }
     ]
    }
   ]
  }
 ]
}