{
 "title": "Marzneshin V1.0.0",
 "description": "this is dashboard for marzneshin pannel with mysql",
 "time": { "from": "2025-03-31T08:30:00.000Z", "to": "2025-04-02T08:29:59.998Z" },
 "refresh": "1m",
 "panels": [
  { "title": "Status now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) 'Online Users', online_at FROM users where online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE) group by online_at"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    nodes.node,\r\n    COALESCE(COUNT(online_users.id), 0) AS users\r\nFROM (\r\n    SELECT DISTINCT IFNULL(n.name, 'Main') AS node FROM nodes n\r\n) AS nodes\r\nLEFT JOIN (\r\n    SELECT \r\n        u.id,\r\n        IFNULL(n.name, 'Main') AS node\r\n    FROM users u\r\n    LEFT JOIN node_user_usages nuu ON nuu.user_id = u.id\r\n    LEFT JOIN nodes n ON n.id = nuu.node_id\r\n    WHERE u.online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\n      AND DATE(nuu.created_at) = CURDATE()\r\n      AND HOUR(nuu.created_at) = HOUR(NOW())\r\n) AS online_users ON nodes.node = online_users.node\r\nGROUP BY nodes.node;\r\n"
    }
   ]
  },
  {
   "title": "Admin List",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  username as \"Name\",\r\n  (SELECT COUNT(*) FROM users WHERE admin_id = admins.id) AS \"Users\"\r\nFROM \r\n  admins\r\n"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "table",
   "description": "Status Lists Nodes",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    name AS 'Name', \r\n    status AS 'Status', \r\n    xray_version,\r\n    CASE \r\n        WHEN uplink >= 1099511627776 THEN CONCAT(ROUND(uplink / 1099511627776, 2), ' TB')\r\n        WHEN uplink >= 1073741824 THEN CONCAT(ROUND(uplink / 1073741824, 2), ' GB')\r\n        WHEN uplink >= 1048576 THEN CONCAT(ROUND(uplink / 1048576, 2), ' MB')\r\n        WHEN uplink >= 1024 THEN CONCAT(ROUND(uplink / 1024, 2), ' KB')\r\n        ELSE CONCAT(uplink, ' B')\r\n    END AS Upload,\r\n    CASE \r\n        WHEN downlink >= 1099511627776 THEN CONCAT(ROUND(downlink / 1099511627776, 2), ' TB')\r\n        WHEN downlink >= 1073741824 THEN CONCAT(ROUND(downlink / 1073741824, 2), ' GB')\r\n        WHEN downlink >= 1048576 THEN CONCAT(ROUND(downlink / 1048576, 2), ' MB')\r\n        WHEN downlink >= 1024 THEN CONCAT(ROUND(downlink / 1024, 2), ' KB')\r\n        ELSE CONCAT(downlink, ' B')\r\n    END AS Down\r\nFROM nodes \r\nWHERE status IN ('unhealthy', 'healthy', 'disabled') \r\nORDER BY status DESC;\r\n"
    }
   ]
  },
  {
   "title": "Connections by Client",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT b.type 'Client',\r\n       count(a.id) 'Users'\r\nFROM users AS a\r\nLEFT JOIN (\r\n    SELECT DISTINCT \r\n           sub_last_user_agent,\r\n           CASE \r\n               WHEN sub_last_user_agent IS NULL OR TRIM(sub_last_user_agent) = '' THEN 'Unknown'  \r\n               ELSE SUBSTR(sub_last_user_agent, 1, INSTR(sub_last_user_agent, '/')-1)\r\n           END AS type\r\n    FROM users\r\n) AS b ON b.sub_last_user_agent = a.sub_last_user_agent\r\nWHERE online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\ngroup by b.type\r\n"
    }
   ]
  },
  {
   "title": "All Used Traffic Overview",
   "type": "stat",
   "description": "حجم کل مصرفی یوزرهای شما (این بخش ریست نخواهد شد)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN SUM(used_traffic) >= 1099511627776 THEN CONCAT(ROUND(SUM(used_traffic) / 1099511627776, 2), ' TB')\r\n    WHEN SUM(used_traffic) >= 1073741824 THEN CONCAT(ROUND(SUM(used_traffic) / 1073741824, 2), ' GB')\r\n    WHEN SUM(used_traffic) >= 1048576 THEN CONCAT(ROUND(SUM(used_traffic) / 1048576, 2), ' MB')\r\n    WHEN SUM(used_traffic) >= 1024 THEN CONCAT(ROUND(SUM(used_traffic) / 1024, 2), ' KB')\r\n    ELSE CONCAT(SUM(used_traffic), ' B')\r\n  END AS total_used_traffic\r\nFROM users\r\n"
    }
   ]
  },
  {
   "title": "All Data Allocation Overview",
   "type": "stat",
   "description": "این قسمت جمع کل حجم های ساخته شده شما هست",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN SUM(data_limit) >= 1099511627776 THEN CONCAT(ROUND(SUM(data_limit) / 1099511627776, 2), ' TB')\r\n    WHEN SUM(data_limit) >= 1073741824 THEN CONCAT(ROUND(SUM(data_limit) / 1073741824, 2), ' GB')\r\n    WHEN SUM(data_limit) >= 1048576 THEN CONCAT(ROUND(SUM(data_limit) / 1048576, 2), ' MB')\r\n    WHEN SUM(data_limit) >= 1024 THEN CONCAT(ROUND(SUM(data_limit) / 1024, 2), ' KB')\r\n    ELSE CONCAT(SUM(data_limit), ' B')\r\n  END AS total_data_limit\r\nFROM users\r\n"
    }
   ]
  },
  {
   "title": "Panel Data Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE \r\n    WHEN downlink >= POWER(1024, 4) THEN CONCAT(ROUND(downlink / POWER(1024, 4), 2), ' TB')\r\n    WHEN downlink >= POWER(1024, 3) THEN CONCAT(ROUND(downlink / POWER(1024, 3), 2), ' GB')\r\n    WHEN downlink >= POWER(1024, 2) THEN CONCAT(ROUND(downlink / POWER(1024, 2), 2), ' MB')\r\n    ELSE CONCAT(ROUND(downlink / 1024, 2), ' KB')\r\n  END AS \"Download\",\r\n\r\n  CASE \r\n    WHEN uplink >= POWER(1024, 4) THEN CONCAT(ROUND(uplink / POWER(1024, 4), 2), ' TB')\r\n    WHEN uplink >= POWER(1024, 3) THEN CONCAT(ROUND(uplink / POWER(1024, 3), 2), ' GB')\r\n    WHEN uplink >= POWER(1024, 2) THEN CONCAT(ROUND(uplink / POWER(1024, 2), 2), ' MB')\r\n    ELSE CONCAT(ROUND(uplink / 1024, 2), ' KB')\r\n  END AS \"Upload\"\r\n  \r\nFROM `system`;"
    }
   ]
  },
  { "title": "Today stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Today users",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select SUM(`a`.`used_traffic`) AS `used_traffic`,\r\n                            ifnull(`n`.`name`, 'Main') AS `node`\r\n                        from ( (\r\n                                    `node_user_usages` `a`\r\n                                    left join `users` `u` on( (`u`.`id` = `a`.`user_id`))\r\n                                )\r\n                                left join `nodes` `n` on( (`n`.`id` = `a`.`node_id`))\r\n                            )\r\n                        where (\r\n                                `a`.`created_at` >= concat( curdate(),' 00:00:00'\r\n                                )\r\n                            )\r\n                            group by ifnull(`n`.`name`, 'Main')"
    }
   ]
  },
  {
   "title": "Traffic by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    IFNULL(`n`.`name`, 'Main') AS `Node`,\r\n    SUM(`a`.`used_traffic`) AS `Traffic`\r\nFROM \r\n    (`node_user_usages` `a` \r\n    LEFT JOIN `users` `u` ON `u`.`id` = `a`.`user_id`) \r\n    LEFT JOIN `nodes` `n` ON `n`.`id` = `a`.`node_id`\r\nWHERE \r\n    CONVERT_TZ(`a`.`created_at`, '+00:00', '+03:30') >= CONCAT(DATE(CONVERT_TZ(NOW(), '+00:00', '+03:30')), ' 00:00:00')\r\nGROUP BY \r\n    IFNULL(`n`.`name`, 'Main');\r\n"
    }
   ]
  },
  {
   "title": "Traffic by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select a.created_at 'Datetime', sum(a.used_traffic) 'Traffic' from node_user_usages a\r\njoin nodes n on n.id = a.node_id\r\nwhere a.created_at >= concat( curdate(),' 00:00:00')\r\ngroup by a.created_at\r\norder by a.created_at ASC\r\n"
    }
   ]
  },
  {
   "title": "Connections by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select a.created_at 'Datetime', count(a.created_at) from node_user_usages a where a.created_at >= concat( curdate(),' 00:00:00') group by a.created_at \r\norder by a.created_at ASC"
    }
   ]
  }
 ]
}