{
 "title": "Marzban-CS V1.1.2",
 "description": "This is the dashboard for the panel representatives with MySQL.",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "adminID", "query": "${VAR_ADMINID}" }
  ]
 },
 "panels": [
  { "title": "Status now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online Users",
   "type": "stat",
   "description": "تعداد کاربرهای انلاین شما اینجا نمایش داده میشه",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  COUNT(id) AS 'Online Users', \r\n  online_at \r\nFROM users \r\nWHERE \r\n  online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\n  AND admin_id = ${adminID}\r\nGROUP BY online_at;\r\n"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "description": "تعداد کاربرهای که به این لوکیشن ها وصل باشند نمایش داده میشه",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "WITH LatestConnection AS (\r\n    SELECT \r\n        user_id, \r\n        node_id,\r\n        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) AS row_num\r\n    FROM node_user_usages \r\n    WHERE DATE(created_at) = CURDATE()\r\n)\r\n\r\nSELECT \r\n    IFNULL(n.name, 'Main') AS node,\r\n    COUNT(u.id) AS users\r\nFROM nodes n\r\nLEFT JOIN LatestConnection lc ON n.id = lc.node_id AND lc.row_num = 1\r\nLEFT JOIN users u ON u.id = lc.user_id AND u.online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE) AND u.admin_id = ${adminID}\r\nGROUP BY n.name\r\nORDER BY users DESC;\r\n"
    }
   ]
  },
  {
   "title": "Admin",
   "type": "table",
   "description": "اطلاعات شما در این بخش (مصرف حجم شما درصورت تمدید ریست خواهد شد)",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  username as \"Name\",\r\n  CASE \r\n    WHEN users_usage >= 1099511627776 THEN CONCAT(ROUND(users_usage / 1099511627776, 2), ' TB')\r\n    WHEN users_usage >= 1073741824 THEN CONCAT(ROUND(users_usage / 1073741824, 2), ' GB')\r\n    WHEN users_usage >= 1048576 THEN CONCAT(ROUND(users_usage / 1048576, 2), ' MB')\r\n    ELSE CONCAT(users_usage, ' B')\r\n  END AS \"Usage\",\r\n  (SELECT COUNT(*) FROM users WHERE admin_id = admins.id) AS \"Users\"\r\nFROM \r\n  admins\r\nWHERE \r\n  admins.id = $adminID;"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "table",
   "description": "وضعیت نودها (فعال غیرفعال نشان داده میشود)",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT name as 'Server Name', status as 'Status', xray_version as 'Xray Version'\r\nFROM nodes \r\nWHERE status IN ('error', 'connecting', 'disabled', 'connected') \r\nORDER BY status DESC;\r\n"
    }
   ]
  },
  {
   "title": "All Data Allocation Overview",
   "type": "stat",
   "description": "این قسمت جمع کل حجم های ساخته شده شما هست",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "alghaede",
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN SUM(data_limit) >= 1099511627776 THEN CONCAT(ROUND(SUM(data_limit) / 1099511627776, 2), ' TB')\r\n    WHEN SUM(data_limit) >= 1073741824 THEN CONCAT(ROUND(SUM(data_limit) / 1073741824, 2), ' GB')\r\n    WHEN SUM(data_limit) >= 1048576 THEN CONCAT(ROUND(SUM(data_limit) / 1048576, 2), ' MB')\r\n    WHEN SUM(data_limit) >= 1024 THEN CONCAT(ROUND(SUM(data_limit) / 1024, 2), ' KB')\r\n    ELSE CONCAT(SUM(data_limit), ' B')\r\n  END AS total_data_limit\r\nFROM users\r\nWHERE admin_id = ${adminID}\r\n"
    }
   ]
  },
  {
   "title": "Connections by Client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT b.type 'Client',\r\n       count(a.id) 'Users'\r\nFROM users AS a\r\nLEFT JOIN (\r\n    SELECT DISTINCT \r\n           sub_last_user_agent,\r\n           CASE \r\n               WHEN sub_last_user_agent IS NULL OR TRIM(sub_last_user_agent) = '' THEN 'Unknown'  \r\n               ELSE SUBSTR(sub_last_user_agent, 1, INSTR(sub_last_user_agent, '/')-1)\r\n           END AS type\r\n    FROM users\r\n) AS b ON b.sub_last_user_agent = a.sub_last_user_agent\r\nWHERE online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\n\tAND a.admin_id = ${adminID}\r\ngroup by b.type\r\n"
    }
   ]
  },
  {
   "title": "All Used Traffic Overview",
   "type": "stat",
   "description": "حجم کل مصرفی یوزرهای شما (این بخش ریست نخواهد شد)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "alghaede",
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN SUM(used_traffic) >= 1099511627776 THEN CONCAT(ROUND(SUM(used_traffic) / 1099511627776, 2), ' TB')\r\n    WHEN SUM(used_traffic) >= 1073741824 THEN CONCAT(ROUND(SUM(used_traffic) / 1073741824, 2), ' GB')\r\n    WHEN SUM(used_traffic) >= 1048576 THEN CONCAT(ROUND(SUM(used_traffic) / 1048576, 2), ' MB')\r\n    WHEN SUM(used_traffic) >= 1024 THEN CONCAT(ROUND(SUM(used_traffic) / 1024, 2), ' KB')\r\n    ELSE CONCAT(SUM(used_traffic), ' B')\r\n  END AS total_used_traffic\r\nFROM users\r\nWHERE admin_id = ${adminID}\r\n"
    }
   ]
  },
  {
   "title": "Reseted Traffic",
   "type": "table",
   "description": "اطلاعات شما در این بخش (مصرف حجم شما درصورت تمدید ریست خواهد شد)",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 9 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n    ad.username AS 'Admin Name',\r\n    a.reset_at,\r\n    -- تبدیل حجم به واحد مناسب با استفاده از CASE\r\n    CASE \r\n        WHEN a.used_traffic_at_reset >= POWER(1024, 4) THEN CONCAT(ROUND(a.used_traffic_at_reset / POWER(1024, 4), 2), ' TB')\r\n        WHEN a.used_traffic_at_reset >= POWER(1024, 3) THEN CONCAT(ROUND(a.used_traffic_at_reset / POWER(1024, 3), 2), ' GB')\r\n        WHEN a.used_traffic_at_reset >= POWER(1024, 2) THEN CONCAT(ROUND(a.used_traffic_at_reset / POWER(1024, 2), 2), ' MB')\r\n        ELSE CONCAT(ROUND(a.used_traffic_at_reset / 1024, 2), ' KB')\r\n    END AS 'Used Traffic'\r\nFROM \r\n    admin_usage_logs a\r\nJOIN \r\n    admins ad ON a.admin_id = ad.id\r\nWHERE \r\n    a.admin_id = ${adminID}\r\nORDER BY \r\n    a.reset_at DESC;\r\n"
    }
   ]
  },
  {
   "title": "All Users Status",
   "type": "bargauge",
   "description": "وضعیت یوزرهای شما",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alghaede",
     "rawSql": "SELECT \r\n    u.status AS \"User Status\", \r\n    COUNT(u.id) AS \"User Count\"\r\nFROM \r\n    users u\r\nWHERE u.admin_id = ${adminID}\r\nGROUP BY \r\n    u.status;\r\n"
    }
   ]
  },
  { "title": "Daily Reset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Today users",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  SUM(a.used_traffic) AS `used_traffic`,\r\n  IFNULL(n.name, 'Main') AS `node`\r\nFROM node_user_usages a\r\nLEFT JOIN users u ON u.id = a.user_id  -- اضافه کردن JOIN برای دسترسی به admin_id\r\nLEFT JOIN nodes n ON n.id = a.node_id\r\nWHERE a.created_at >= CONCAT(CURDATE(), ' 00:00:00')\r\n  AND u.admin_id = ${adminID}  -- فیلتر کردن فقط برای یک ادمین خاص\r\nGROUP BY IFNULL(n.name, 'Main');\r\n"
    }
   ]
  },
  {
   "title": "Traffic by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  IFNULL(n.name, 'Main') AS `Node`,\r\n  SUM(a.used_traffic) AS `Traffic`\r\nFROM node_user_usages AS a\r\nLEFT JOIN users AS u ON u.id = a.user_id\r\nLEFT JOIN nodes AS n ON n.id = a.node_id\r\nWHERE \r\n  CONVERT_TZ(a.created_at, '+00:00', '+03:30') >= CONCAT(DATE(CONVERT_TZ(NOW(), '+00:00', '+03:30')), ' 00:00:00')\r\n  AND u.admin_id = ${adminID} \r\nGROUP BY \r\n  IFNULL(n.name, 'Main');\r\n"
    }
   ]
  },
  {
   "title": "Traffic by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  a.created_at AS 'Datetime', \r\n  SUM(a.used_traffic) AS 'Traffic'\r\nFROM node_user_usages a\r\nJOIN nodes n ON n.id = a.node_id\r\nJOIN users u ON u.id = a.user_id\r\nWHERE a.created_at >= CONCAT(CURDATE(), ' 00:00:00')\r\n  AND u.admin_id = ${adminID}\r\nGROUP BY a.created_at\r\nORDER BY a.created_at ASC;\r\n"
    }
   ]
  },
  {
   "title": "Connections by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT \r\n  a.created_at AS 'Datetime', \r\n  COUNT(a.created_at) AS 'Count'\r\nFROM node_user_usages a\r\nJOIN users u ON u.id = a.user_id\r\nWHERE a.created_at >= CONCAT(CURDATE(), ' 00:00:00')\r\n  AND u.admin_id = ${adminID}\r\nGROUP BY a.created_at\r\nORDER BY a.created_at ASC;"
    }
   ]
  }
 ]
}